# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dca072c2ae1e6f85296565f1e3fa43f29fd7883b3ae424e3bbd59eb5ab7c5e2eec4031542170dd7da132adac0122f42b01711b15dc566bbfa748a9f2a8d3c0e

test:
  secret_key_base: cc7aca45a935417be7cb7f0fa2494243842999920ae54a63beb20f3b31d05585eda52e5869c5b96879fcb6834278e76960bf488b5ce69866dab17c1e9b4c790d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
